"use client"

import { useState } from "react"
import { SidebarNav } from "@/components/dashboard/sidebar-nav"
import { Header } from "@/components/dashboard/header"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu"
import {
  Search,
  Clock,
  Layers,
  Microscope,
  FileText,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Server,
} from "lucide-react"
import Link from "next/link"
import {
  mockIncidents,
  formatTimeAgo,
  getSeverityBadgeClass,
  getStatusDotClass,
  getStatusLabel,
  type IncidentStatus,
} from "@/lib/mock-data"
import { cn } from "@/lib/utils"

const ITEMS_PER_PAGE = 10

function avgCorrelationScore(alerts: { correlation?: { score: number } }[]): number | null {
  const scored = alerts.filter((a) => a.correlation !== undefined)
  if (scored.length === 0) return null
  return Math.round(scored.reduce((sum, a) => sum + a.correlation!.score, 0) / scored.length)
}

export default function IncidentsPage() {
  const [searchQuery, setSearchQuery] = useState("")
  const [statusFilter, setStatusFilter] = useState("all")
  const [severityFilter, setSeverityFilter] = useState("all")
  const [currentPage, setCurrentPage] = useState(1)

  const filteredIncidents = mockIncidents.filter((incident) => {
    const matchesSearch =
      incident.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      incident.id.toLowerCase().includes(searchQuery.toLowerCase())
    const matchesStatus =
      statusFilter === "all" || incident.status === statusFilter
    const matchesSeverity =
      severityFilter === "all" || incident.severity === severityFilter
    return matchesSearch && matchesStatus && matchesSeverity
  })

  const totalPages = Math.ceil(filteredIncidents.length / ITEMS_PER_PAGE)
  const paginatedIncidents = filteredIncidents.slice(
    (currentPage - 1) * ITEMS_PER_PAGE,
    currentPage * ITEMS_PER_PAGE
  )

  const showPagination = totalPages > 1

  return (
    <div className="flex min-h-screen bg-background">
      <SidebarNav />

      <div className="flex-1 flex flex-col">
        <Header
          title="Incidents"
          subtitle="Manage and track all incidents"
        />

        <main className="flex-1 p-6 overflow-auto">
          {/* Incidents are generated by the correlation engine — no manual creation. */}
          <Card className="bg-card border-border mb-6">
            <CardContent className="p-4">
              <div className="flex flex-wrap items-center gap-4">
                <div className="relative flex-1 min-w-64">
                  <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
                  <Input
                    placeholder="Search incidents..."
                    value={searchQuery}
                    onChange={(e) => setSearchQuery(e.target.value)}
                    className="pl-9 bg-secondary border-border"
                  />
                </div>

                <Select value={statusFilter} onValueChange={setStatusFilter}>
                  <SelectTrigger className="w-44 bg-secondary border-border">
                    <SelectValue placeholder="Status" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All status</SelectItem>
                    <SelectItem value="detected">Detected</SelectItem>
                    <SelectItem value="investigating">Investigating</SelectItem>
                    <SelectItem value="waiting_for_review">Waiting for review</SelectItem>
                    <SelectItem value="reinvestigating">Reinvestigating</SelectItem>
                    <SelectItem value="validated">Validated</SelectItem>
                    <SelectItem value="aborted">Aborted</SelectItem>
                  </SelectContent>
                </Select>

                <Select value={severityFilter} onValueChange={setSeverityFilter}>
                  <SelectTrigger className="w-36 bg-secondary border-border">
                    <SelectValue placeholder="Severity" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="all">All severity</SelectItem>
                    <SelectItem value="critical">Critical</SelectItem>
                    <SelectItem value="warning">Warning</SelectItem>
                    <SelectItem value="unknown">Unknown</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </CardContent>
          </Card>

          <Card className="bg-card border-border">
            <CardHeader className="pb-3 flex flex-row items-center justify-between">
              <CardTitle className="text-base font-medium">
                All incidents ({filteredIncidents.length})
              </CardTitle>
              {showPagination && (
                <div className="flex items-center gap-2 text-sm text-muted-foreground">
                  Page {currentPage} of {totalPages}
                </div>
              )}
            </CardHeader>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow className="border-border hover:bg-transparent">
                    <TableHead className="text-muted-foreground">ID</TableHead>
                    <TableHead className="text-muted-foreground">Title</TableHead>
                    <TableHead className="text-muted-foreground">Severity</TableHead>
                    <TableHead className="text-muted-foreground">Status</TableHead>
                    <TableHead className="text-muted-foreground">Services</TableHead>
                    <TableHead className="text-muted-foreground">Alerts</TableHead>
                    <TableHead className="text-muted-foreground">Created</TableHead>
                    <TableHead className="text-muted-foreground w-10" />
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {paginatedIncidents.map((incident) => {
                    const avgScore = avgCorrelationScore(incident.alerts)
                    return (
                      <TableRow
                        key={incident.id}
                        className="border-border hover:bg-secondary/30"
                      >
                        <TableCell className="font-mono text-sm">
                          <Link
                            href={`/incidents/${incident.id}`}
                            className="hover:text-accent transition-colors"
                          >
                            {incident.id}
                          </Link>
                        </TableCell>
                        <TableCell className="max-w-xs">
                          <Link
                            href={`/incidents/${incident.id}`}
                            className="block group"
                          >
                            <div className="truncate font-medium group-hover:text-accent transition-colors">
                              {incident.title}
                            </div>
                            {incident.aiSummary && (
                              <p className="text-xs text-muted-foreground truncate mt-1">
                                {incident.aiSummary}
                              </p>
                            )}
                          </Link>
                        </TableCell>
                        <TableCell>
                          <Badge
                            className={cn(
                              "text-xs capitalize",
                              getSeverityBadgeClass(incident.severity)
                            )}
                          >
                            {incident.severity}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <Badge
                            variant="outline"
                            className="text-xs capitalize gap-1.5 bg-secondary text-foreground border-border"
                          >
                            <span
                              className={cn(
                                "w-1.5 h-1.5 rounded-full",
                                getStatusDotClass(incident.status as IncidentStatus),
                              )}
                              aria-hidden="true"
                            />
                            {getStatusLabel(incident.status as IncidentStatus)}
                          </Badge>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-1 flex-wrap max-w-[220px]">
                            {incident.affectedServices.slice(0, 2).map((svc) => (
                              <span
                                key={svc}
                                className="inline-flex items-center gap-1 rounded border border-border bg-secondary px-1.5 py-0.5 text-[10px] font-mono text-muted-foreground"
                              >
                                <Server className="w-2.5 h-2.5" />
                                {svc}
                              </span>
                            ))}
                            {incident.affectedServices.length > 2 && (
                              <span
                                className="inline-flex items-center rounded border border-border bg-secondary px-1.5 py-0.5 text-[10px] font-mono text-muted-foreground"
                                title={incident.affectedServices.slice(2).join(", ")}
                              >
                                +{incident.affectedServices.length - 2}
                              </span>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-2 text-sm text-muted-foreground">
                            <span className="flex items-center gap-1">
                              <Layers className="w-3 h-3" />
                              {incident.alerts.length}
                            </span>
                            {avgScore !== null && (
                              <Badge
                                variant="outline"
                                className="text-[10px] px-1.5 py-0 h-4 font-mono text-muted-foreground border-border"
                                title="Average correlation score"
                              >
                                {avgScore}
                              </Badge>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>
                          <div className="flex items-center gap-1 text-sm text-muted-foreground">
                            <Clock className="w-3 h-3" />
                            {formatTimeAgo(incident.createdAt)}
                          </div>
                        </TableCell>
                        <TableCell>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                className="h-8 w-8"
                                aria-label={`Actions for ${incident.id}`}
                              >
                                <MoreHorizontal className="w-4 h-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="end">
                              <DropdownMenuItem asChild>
                                <Link href={`/incidents/${incident.id}/investigation`}>
                                  <Microscope className="w-4 h-4 mr-2" />
                                  Open investigation
                                </Link>
                              </DropdownMenuItem>
                              <DropdownMenuItem asChild>
                                <Link href={`/incidents/${incident.id}/report`}>
                                  <FileText className="w-4 h-4 mr-2" />
                                  View report
                                </Link>
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </TableCell>
                      </TableRow>
                    )
                  })}
                </TableBody>
              </Table>
            </CardContent>

            {showPagination && (
              <div className="flex items-center justify-between px-6 py-4 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  Showing {(currentPage - 1) * ITEMS_PER_PAGE + 1} to{" "}
                  {Math.min(currentPage * ITEMS_PER_PAGE, filteredIncidents.length)} of{" "}
                  {filteredIncidents.length} incidents
                </p>
                <div className="flex items-center gap-2">
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
                    disabled={currentPage === 1}
                  >
                    <ChevronLeft className="w-4 h-4 mr-1" />
                    Previous
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
                    disabled={currentPage === totalPages}
                  >
                    Next
                    <ChevronRight className="w-4 h-4 ml-1" />
                  </Button>
                </div>
              </div>
            )}
          </Card>
        </main>
      </div>
    </div>
  )
}
